const opportunities = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "NovaTech AI",
    industry: "Technology",
    workType: "Remote",
    employment: "Full-time",
    deadline: "7d",
    salary: "$2,500 - $3,500",
    experience: "2+ Years",
    skills: ["React", "Next.js", "Tailwind CSS"],
    description:
      "Build modern and responsive web applications using React and Next.js.",
    responsibilities: [
      "Develop responsive UI",
      "Collaborate with backend developers",
      "Optimize application performance",
    ],
    requirements: ["React", "Next.js", "Tailwind CSS", "Git"],
  },

  {
    id: 2,
    title: "Backend Engineer",
    company: "CloudMatrix",
    industry: "SaaS",
    workType: "Remote",
    employment: "Full-time",
    deadline: "13d",
    salary: "$3,000 - $4,500",
    experience: "3+ Years",
    skills: ["Node.js", "Express", "MongoDB"],
    description: "Develop secure backend APIs and scalable cloud services.",
    responsibilities: ["Create REST APIs", "Database Design", "Authentication"],
    requirements: ["Node.js", "MongoDB", "JWT"],
  },

  {
    id: 3,
    title: "React Native Developer",
    company: "CarePulse",
    industry: "HealthTech",
    workType: "Hybrid",
    employment: "Full-time",
    deadline: "Expired",
    salary: "$2,800 - $4,000",
    experience: "2 Years",
    skills: ["React Native", "Redux"],
    description: "Develop cross-platform healthcare mobile applications.",
    responsibilities: [
      "Build mobile apps",
      "API Integration",
      "Performance Optimization",
    ],
    requirements: ["React Native", "Redux", "Firebase"],
  },

  {
    id: 4,
    title: "QA Automation Engineer",
    company: "PayNexus",
    industry: "FinTech",
    workType: "Hybrid",
    employment: "Contract",
    deadline: "Expired",
    salary: "$2,200 - $3,000",
    experience: "2 Years",
    skills: ["Playwright", "TypeScript", "CI/CD"],
    description: "Ensure software quality through automated testing.",
    responsibilities: ["Write Test Cases", "Automation", "Bug Reporting"],
    requirements: ["Playwright", "GitHub Actions"],
  },

  {
    id: 5,
    title: "Unity 3D Engineer",
    company: "EduSphere",
    industry: "EdTech",
    workType: "Onsite",
    employment: "Full-time",
    deadline: "13d",
    salary: "$2,500 - $3,800",
    experience: "2+ Years",
    skills: ["Unity", "C#", "Shader Graph"],
    description: "Create immersive educational VR experiences.",
    responsibilities: ["Develop VR apps", "Optimize graphics"],
    requirements: ["Unity", "C#"],
  },

  {
    id: 6,
    title: "UI/UX Designer",
    company: "CarePulse",
    industry: "HealthTech",
    workType: "Remote",
    employment: "Part-time",
    deadline: "13d",
    salary: "$1,500 - $2,500",
    experience: "2 Years",
    skills: ["Figma", "Design System"],
    description: "Design user-friendly healthcare products.",
    responsibilities: ["Wireframing", "Prototype"],
    requirements: ["Figma", "UX Research"],
  },

  {
    id: 7,
    title: "Full Stack Developer",
    company: "Microsoft",
    industry: "Technology",
    workType: "Remote",
    employment: "Full-time",
    deadline: "16d",
    salary: "$4,000 - $6,000",
    experience: "3+ Years",
    skills: ["React", "Node.js"],
    description: "Develop full-stack enterprise applications.",
    responsibilities: ["Frontend", "Backend"],
    requirements: ["React", "Node", "MongoDB"],
  },

  {
    id: 8,
    title: "AI Engineer",
    company: "VisionAI Labs",
    industry: "AI/ML",
    workType: "Hybrid",
    employment: "Full-time",
    deadline: "5d",
    salary: "$5,000 - $7,000",
    experience: "4 Years",
    skills: ["Python", "TensorFlow", "PyTorch"],
    description: "Develop next-generation AI products.",
    responsibilities: ["Model Training", "Deployment"],
    requirements: ["Python", "TensorFlow"],
  },

  {
    id: 9,
    title: "Marketing Executive",
    company: "TravelNest",
    industry: "Other",
    workType: "Remote",
    employment: "Part-time",
    deadline: "20d",
    salary: "$1,200 - $2,000",
    experience: "1 Year",
    skills: ["SEO", "Marketing"],
    description: "Promote travel products through digital marketing.",
    responsibilities: ["SEO", "Campaign Management"],
    requirements: ["Google Ads", "SEO"],
  },

  {
    id: 10,
    title: "DevOps Engineer",
    company: "GreenPulse",
    industry: "Green Tech",
    workType: "Hybrid",
    employment: "Full-time",
    deadline: "10d",
    salary: "$3,500 - $5,000",
    experience: "3 Years",
    skills: ["Docker", "AWS", "CI/CD"],
    description: "Manage cloud infrastructure and deployments.",
    responsibilities: ["AWS", "Docker", "Monitoring"],
    requirements: ["Docker", "AWS", "Linux"],
  },

  {
    id: 11,
    title: "Product Designer",
    company: "PixelCraft",
    industry: "SaaS",
    workType: "Hybrid",
    employment: "Part-time",
    deadline: "9d",
    salary: "$2,500 - $3,800",
    experience: "2+ Years",
    skills: ["Figma", "UI Design", "Prototype"],
    description: "Create modern and user-friendly product interfaces.",
  },

  {
    id: 12,
    title: "Machine Learning Engineer",
    company: "VisionMind AI",
    industry: "AI/ML",
    workType: "Remote",
    employment: "Full-time",
    deadline: "18d",
    salary: "$4,500 - $7,000",
    experience: "3+ Years",
    skills: ["Python", "TensorFlow", "PyTorch"],
    description: "Build intelligent AI models for real-world applications.",
  },
];

module.exports = opportunities;
